-- V1: Baseline schema for the embedded H2 database.
--
-- This consolidates the former MySQL migration chain (V1-V8) into the final
-- shape of the schema, written in portable/H2 syntax. The MySQL-only pieces it
-- replaces were: ENGINE/CHARSET clauses, inline INDEX definitions,
-- `ON UPDATE CURRENT_TIMESTAMP`, `MODIFY COLUMN` and `DROP FOREIGN KEY`.
--
-- Identity columns are GENERATED BY DEFAULT (not ALWAYS) so that a data import
-- can supply explicit primary keys; the sequences are then restarted past the
-- highest imported id.
--
-- created_at/updated_at are maintained by JPA (@PrePersist/@PreUpdate); the
-- defaults below only serve rows inserted through plain SQL.

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    color VARCHAR(7) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    color VARCHAR(7),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date DATE NOT NULL,
    transaction_type VARCHAR(10) NOT NULL,
    original_amount DECIMAL(15,2) NOT NULL,
    original_currency VARCHAR(3) NOT NULL,
    conversion_rate DECIMAL(10,4),
    amount_krw DECIMAL(15,2) NOT NULL,
    category_id BIGINT NOT NULL,
    memo VARCHAR(65535),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transaction_category FOREIGN KEY (category_id)
        REFERENCES category (id) ON DELETE RESTRICT,
    CONSTRAINT chk_amount_positive CHECK (original_amount > 0),
    CONSTRAINT chk_amount_krw_positive CHECK (amount_krw > 0),
    CONSTRAINT chk_conversion_rate_range CHECK (
        conversion_rate IS NULL OR (conversion_rate >= 0.01 AND conversion_rate <= 10000)
    )
);

CREATE INDEX idx_transaction_date ON transaction (transaction_date);
CREATE INDEX idx_transaction_type ON transaction (transaction_type);
CREATE INDEX idx_transaction_category_id ON transaction (category_id);
CREATE INDEX idx_transaction_created_at ON transaction (created_at);
CREATE INDEX idx_transaction_amount_krw ON transaction (amount_krw);

CREATE TABLE transaction_tag (
    transaction_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (transaction_id, tag_id),
    CONSTRAINT fk_transaction_tag_transaction FOREIGN KEY (transaction_id)
        REFERENCES transaction (id) ON DELETE CASCADE,
    CONSTRAINT fk_transaction_tag_tag FOREIGN KEY (tag_id)
        REFERENCES tag (id) ON DELETE CASCADE
);

CREATE TABLE session_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key VARCHAR(100) NOT NULL UNIQUE,
    theme VARCHAR(10) DEFAULT 'LIGHT',
    default_currency VARCHAR(3) DEFAULT 'KRW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
